### ISSUE TITLE
Week 4

### ISSUE THREAD

**Issue by pop** [XZES40/XZES40-Transformer#25]
This week we will each accomplish the following:

@Todopen 

- [x] Begin work on caching documents ( #8 ). Prototype.
- [x] Ensure #23 is complete.
- Begin work on assignment.

@zixunlu 

- [x] Upload benchmark document
- [x] Finish benchmark document
- [x] Fix Pull Request #23 
- Begin work on assignment.

@elijahcaine

- [x] Finish #23 
- [x] Begin work on daemonizing the application ( #26 ) Prototype
- Begin work on assignment
